### PR TITLE
Remove unnecessary python dependency

### PR DESCRIPTION
**Pull request by Krista-Rogers**
Hi Richard,

As we spoke about earlier, I'm removing this excess dependency.

This isn't required as it is present in the Makefile [here](https://github.com/Metaswitch/sasclient.py/blob/master/Makefile#L39).

### CODE REVIEW

**Comment by richardwhiuk** [comment]
Have you tested `make coverage` works on a clean checkout (preferably having run `git clean -fXD`)?

**Review by richardwhiuk — APPROVED** [review]
Apart from that, looks fine :shipit:

**Comment by Krista-Rogers** [comment]
I hadn't run "make coverage", only "make test".
With this change in place, "make coverage" fails.

I've edited the Makefile to be consistent with other Makefiles.
Now "make test", "make env" and "make coverage" all succeed.

**Comment by richardwhiuk** [comment]
Looks fine.

**Pull request merged**
